name: GDCorp Publish Docker image
on:
  release:
    types: [ published ]
jobs:
  push_to_registry:
    name: Push Docker image to GitHub Packages
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - name: Check out the repo
        uses: actions/checkout@HEAD
      - name: Build and publish
        run: 
          # new login with new container registry url and PAT
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin
          docker pull ghcr.io/gdcorp-action-public-forks:latest
          docker build . --tag ghcr.io/gdcorp-action-public-forks:$GITHUB_SHA --cache-from ghcr.io/gdcorp-action-public-forks:latest
          docker push ghcr.io/gdcorp-action-public-forks/super-linter:$GITHUB_SHA
